name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      id: build
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          cargo build --release
    - name: Test
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          cargo test --verbose
